# 1. Variables and Datatypes
# Write a Python program to store your name, age, and height in variables and print their types.

# 2. Arithmetic Operators
# Write a Python program to input two numbers and print their sum, difference, product, and quotient.

# 3. List – Append and Remove
# Create a list of 5 fruits, add one more fruit, and remove one existing fruit.

# 4. Tuple – Access Elements
# Create a tuple of 4 numbers and print the first and last elements.

# 5. Dictionary – Access and Update
# Create a dictionary with keys name, age, and city. Change the city and print the updated dictionary.

# 6. List Methods – Sort and Reverse
# Create a list of numbers, sort it, then reverse it.

# 7. Comparison and Logical Operators
# Check if a number is positive and even using logical operators.

# 8. Dictionary Methods – keys(), values(), items()
# Create a dictionary and display all its keys, values, and key-value pairs using dictionary methods.





#  Task Two


# 1. Variables and Datatypes
# Assign values to variables for the cost of three items and calculate the total and average cost.

# 2. Arithmetic Operators
# Use arithmetic operators to calculate the area and perimeter of a rectangle using fixed values for length and width.

# 3. List – 
# Create a list of colors, append two new colors, and remove one existing color.

# 4. List – 
# Create a list of 5 integers, insert a new number at the second position, and remove the last element.

# 5. List – 
# Create a list of numbers, sort it in ascending order, then reverse the order.

# 6. Tuple – 
# Create a tuple of 6 numbers and print the first, middle, and last elements.

# 7. Tuple – 
# Create a tuple containing repeated values and  display the frequency and position of a specific element.

# 8. Dictionary – 
# Create a dictionary with keys as subject names and values as marks. Print marks for two specific subjects.

# 9. Dictionary – 
# Create a dictionary with employee details and update the salary, then add a new key for department.

# 10. Dictionary – 
# Create a dictionary of three city names with their populations. Delete one entry and then clear all entries.

# 11. Operators – 
# Write code to check if the sum of two numbers is greater than a third number.

# 12. Operators – 
# Check if a number is positive and divisible by 5.

# 13. List and Dictionary Combination
# Create a dictionary where each key is a student's name and the value is a list of their marks. Print one student's marks.

# 14. Tuple and List Conversion
# Create a tuple of fruits, convert it to a list, add one more fruit, and convert it back to a tuple.

# 15. Dictionary Methods – 
# Create a dictionary with three countries and their capitals. Display all keys, values, and items using dictionary methods.
